version: 2
updates:

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  ignore:
    # Since this package is a library, we don't need patch updates to
    # production dependencies and peer dependencies.
    # We might want patch updates of non-peer dev dependencies
    # but most of the dev dependencies are peer dependencies
    # so we just ignore all patch updates for simplicity.
    - dependency-name: "*"
      update-types: ["version-update:semver-patch"]
  open-pull-requests-limit: 10

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
