name: Build Snapshot

on:
  pull_request:
    types: [opened, synchronize, reopened, edited] # TODO: this line is for debug

permissions:
  contents: read

jobs:
  build:
    name: Build Snapshot

    runs-on: ubuntu-latest

    steps:
    - name: Prepare temporary directory
      run: |
        tmpdir="$(mktemp -d)"
        echo ::set-output name=TMPDIR::$tmpdir
        mkdir "$tmpdir/before"
        mkdir "$tmpdir/after"
        ls "$tmpdir" # TODO: remove debug command
      id: tmpdir

    # TODO: DRY duplicate steps for 'before' and 'after'

    # Generate snapshots of 'before'

    - name: Checkout 'before'
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}
        persist-credentials: false

    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm_before

    - name: Use Node.js ${{ steps.nvm_before.outputs.NVMRC }}
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm_before.outputs.NVMRC }}"

    - run: npm ci

    - name: Generate Snapshot
      run: |
        yarn run --silent eslint --print-config script.ts >> "${{ steps.tmpdir.outputs.TMPDIR }}/before/typescript-ts.json"
        # TODO: add other snapshots

    # Generate snapshots of 'after'

    - name: Checkout 'after'
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        persist-credentials: false

    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm_after

    - name: Use Node.js ${{ steps.nvm_after.outputs.NVMRC }}
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm_after.outputs.NVMRC }}"

    - run: npm ci

    - name: Generate Snapshot
      run: |
        yarn run --silent eslint --print-config script.ts >> "${{ steps.tmpdir.outputs.TMPDIR }}/after/typescript-ts.json"
        # TODO: add other snapshots
    
    # End of generating snapshots

    - name: Generate diff
      run: |
        git diff --compact-summary "${{ steps.tmpdir.outputs.TMPDIR }}/before" "${{ steps.tmpdir.outputs.TMPDIR }}/after" >> "${{ steps.tmpdir.outputs.TMPDIR }}/diff-summary.txt" || true
        git diff "${{ steps.tmpdir.outputs.TMPDIR }}/before" "${{ steps.tmpdir.outputs.TMPDIR }}/after" >> "${{ steps.tmpdir.outputs.TMPDIR }}/diff-complete.diff" || true

    - name: Upload snapshots
      uses: actions/upload-artifact@v2
      with:
        name: snapshots
        path: ${{ steps.tmpdir.outputs.TMPDIR }}
